//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca_Entity.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carreras
    {
        public int id_carreras { get; set; }
        public string nombre { get; set; }
        public Nullable<int> duracion { get; set; }
    }
}
