//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca_Entity.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libros()
        {
            this.DetallesLibros = new HashSet<DetallesLibros>();
        }
    
        public int id_isbn { get; set; }
        public Nullable<int> id_autor { get; set; }
        public Nullable<int> id_editorial { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<int> id_idioma { get; set; }
        public string titulo { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<System.DateTime> fecha_publicacion { get; set; }
    
        public virtual autores autores { get; set; }
        public virtual Categorias Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesLibros> DetallesLibros { get; set; }
        public virtual Editoriales Editoriales { get; set; }
        public virtual Idiomas Idiomas { get; set; }
        public virtual Libros_Alumnos Libros_Alumnos { get; set; }
    }
}
