//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca_Entity.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros_Alumnos
    {
        public int id_isbn { get; set; }
        public Nullable<int> id_dni { get; set; }
        public Nullable<System.DateTime> fehca_entrega { get; set; }
        public Nullable<System.DateTime> fehca_devolucion { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Libros Libros { get; set; }
    }
}
